root: ./

structure:
  readme: README.md
  summary: SUMMARY.md
  images: assets/banner.png

redirects:
  docs/getting-started/security-setup: antivirus.md
  getting-started/prerequisites: docs/getting-started/prerequisites.md
  getting-started/security-setup: docs/getting-started/security-setup.md
  getting-started/installation: docs/getting-started/installation.md
  additional-resources/faq: docs/additional-resources/faq.md
  additional-resources/troubleshooting: docs/additional-resources/troubleshooting.md
  additional-resources/changelog: docs/additional-resources/changelog.md